fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.7.0'
    archive:
      repo: 'puppet/archive'
      ref: '0.4.4'
  symlinks:
    oracle_java: "#{source_dir}"     
